version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/angular-app:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: ["npm", "start"]

  db:
    image: postgres:14
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_config:/tmp/jenkins_config
      - ./backend:/var/jenkins_home/backend
      - ./frontend:/var/jenkins_home/frontend

volumes:
  db_data:
  jenkins_home:
