version: '3.9'

services:
  backend:
    build:
      context: ./backend
      target: test
    volumes:
      - ./backend:/app
    environment:
      - TESTING=true
    depends_on:
      - test_db

  frontend:
    build:
      context: ./frontend
      target: test
    volumes:
      - ./frontend/angular-app:/app
      - /app/node_modules

  test_db:
    image: postgres:14
    env_file:
      - ./backend/.env.test
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  db_data:
